[
  {
    id: "po_box_address_proof",
    name: "PO Box Address Proof",
    category: "address_proof",
    requiredFor: ["beneficiary"],
    required: false,
  },
  {
    id: "property_tax_bills",
    name: "Property Tax Bills",
    category: "address_proof",
    requiredFor: ["beneficiary", "petitioner"],
    required: false,
  },
  {
    id: "rent_agreement",
    name: "Rent Agreement",
    category: "address_proof",
    requiredFor: ["beneficiary"],
    required: false,
  },
  {
    id: "utility_bills_pk",
    name: "Utility Bills (Pakistan)",
    category: "address_proof",
    requiredFor: ["beneficiary"],
    required: false,
  },

  {
    id: "birth_certificate",
    name: "Birth Certificate",
    category: "civil",
    requiredFor: ["beneficiary"],
    required: true,
  },
  {
    id: "cnic",
    name: "CNIC (Computerized National Identity Card)",
    category: "civil",
    requiredFor: ["beneficiary"],
    required: true,
  },
  {
    id: "nikah_nama",
    name: "Nikah Nama (Marriage Certificate)",
    category: "civil",
    requiredFor: ["beneficiary"],
    required: true,
  },
  {
    id: "passport_copy",
    name: "Passport Copy",
    category: "civil",
    requiredFor: ["beneficiary"],
    required: true,
  },

  {
    id: "bachelors_degree",
    name: "Bachelor's Degree",
    category: "education",
    requiredFor: ["beneficiary"],
    required: false,
  },
  {
    id: "hec_attestation",
    name: "HEC Attestation",
    category: "education",
    requiredFor: ["beneficiary"],
    required: false,
  },
  {
    id: "intermediate_certificate",
    name: "Intermediate Certificate",
    category: "education",
    requiredFor: ["beneficiary"],
    required: false,
  },
  {
    id: "masters_degree",
    name: "Master's Degree",
    category: "education",
    requiredFor: ["beneficiary"],
    required: false,
  },
  {
    id: "matric_certificate",
    name: "Matriculation Certificate",
    category: "education",
    requiredFor: ["beneficiary"],
    required: false,
  },
  {
    id: "professional_certifications",
    name: "Professional Certifications",
    category: "education",
    requiredFor: ["beneficiary"],
    required: false,
  },

  {
    id: "bank_statements",
    name: "Bank Statements",
    category: "financial",
    requiredFor: ["petitioner"],
    required: false,
  },
  {
    id: "employment_verification_letter",
    name: "Employment Verification Letter",
    category: "financial",
    requiredFor: ["petitioner"],
    required: true,
  },
  {
    id: "form_i864",
    name: "Form I-864 (Affidavit of Support)",
    category: "financial",
    requiredFor: ["petitioner"],
    required: true,
  },
  {
    id: "irs_tax_returns",
    name: "IRS Tax Returns (3 years)",
    category: "financial",
    requiredFor: ["petitioner"],
    required: true,
  },
  {
    id: "pay_stubs",
    name: "Recent Pay Stubs",
    category: "financial",
    requiredFor: ["petitioner"],
    required: true,
  },
  {
    id: "w2_forms",
    name: "W-2 Forms",
    category: "financial",
    requiredFor: ["petitioner"],
    required: false,
  },

  {
    id: "health_insurance_policy",
    name: "Health Insurance Policy",
    category: "health",
    requiredFor: ["beneficiary", "petitioner"],
    required: false,
  },
  {
    id: "insurance_coverage_letter",
    name: "Insurance Coverage Letter",
    category: "health",
    requiredFor: ["petitioner"],
    required: false,
  },

  {
    id: "domicile_certificate",
    name: "Domicile Certificate",
    category: "identity",
    requiredFor: ["beneficiary"],
    required: false,
  },
  {
    id: "driving_license",
    name: "Driving License (Pakistan)",
    category: "identity",
    requiredFor: ["beneficiary"],
    required: false,
  },
  {
    id: "nicop",
    name: "NICOP/CNIC with Photo",
    category: "identity",
    requiredFor: ["beneficiary"],
    required: false,
  },
  {
    id: "prc",
    name: "PRC (Permanent Residence Certificate)",
    category: "identity",
    requiredFor: ["beneficiary"],
    required: false,
  },

  {
    id: "i94_records",
    name: "Arrival/Departure Records (I-94)",
    category: "immigration",
    requiredFor: ["beneficiary"],
    required: false,
  },
  {
    id: "prior_petition_docs",
    name: "Prior Immigration Petition Documents",
    category: "immigration",
    requiredFor: ["beneficiary", "petitioner"],
    required: false,
  },
  {
    id: "reentry_permit",
    name: "Re-entry Permit",
    category: "immigration",
    requiredFor: ["beneficiary"],
    required: false,
  },

  {
    id: "affidavit_marriage",
    name: "Affidavit of Bona Fide Marriage",
    category: "legal",
    requiredFor: ["beneficiary", "petitioner"],
    required: false,
  },
  {
    id: "guardianship_docs",
    name: "Guardianship/Custody Documents",
    category: "legal",
    requiredFor: ["beneficiary", "petitioner"],
    required: false,
  },
  {
    id: "name_change_docs",
    name: "Name Change Documents",
    category: "legal",
    requiredFor: ["beneficiary", "petitioner"],
    required: false,
  },
  {
    id: "notarized_docs",
    name: "Notarized Documents",
    category: "legal",
    requiredFor: ["beneficiary", "petitioner"],
    required: false,
  },

  {
    id: "medical_exam",
    name: "Medical Examination (Form DS-2019)",
    category: "medical",
    requiredFor: ["beneficiary"],
    required: true,
  },
  {
    id: "polio_certificate",
    name: "Polio Vaccination Certificate",
    category: "medical",
    requiredFor: ["beneficiary"],
    required: true,
  },
  {
    id: "vaccination_records",
    name: "Vaccination Records",
    category: "medical",
    requiredFor: ["beneficiary"],
    required: true,
  },

  {
    id: "ds260",
    name: "Form DS-260",
    category: "misc",
    requiredFor: ["beneficiary"],
    required: true,
  },
  {
    id: "i130_approval",
    name: "Form I-130 Approval Notice",
    category: "misc",
    requiredFor: ["petitioner"],
    required: true,
  },
  {
    id: "nvc_receipts",
    name: "NVC Fee Payment Receipts",
    category: "misc",
    requiredFor: ["petitioner"],
    required: true,
  },

  {
    id: "interview_notes",
    name: "Consular Interview Notes",
    category: "other",
    requiredFor: ["beneficiary"],
    required: false,
  },
  {
    id: "correspondence_logs",
    name: "Correspondence Logs",
    category: "other",
    requiredFor: ["beneficiary", "petitioner"],
    required: false,
  },
  {
    id: "cover_letter",
    name: "Cover Letter",
    category: "other",
    requiredFor: ["beneficiary", "petitioner"],
    required: false,
  },
  {
    id: "relationship_timeline",
    name: "Relationship Timeline",
    category: "other",
    requiredFor: ["beneficiary", "petitioner"],
    required: false,
  },

  {
    id: "passport_photos",
    name: "Passport-Style Photos",
    category: "photos",
    requiredFor: ["beneficiary"],
    required: true,
  },

  {
    id: "court_records",
    name: "Court Records",
    category: "police",
    requiredFor: ["beneficiary"],
    required: false,
  },
  {
    id: "police_certificate",
    name: "Police Certificate (Pakistan)",
    category: "police",
    requiredFor: ["beneficiary"],
    required: true,
  },

  {
    id: "bank_assets",
    name: "Bank Assets in Pakistan",
    category: "assets",
    requiredFor: ["beneficiary", "petitioner"],
    required: false,
  },
  {
    id: "investment_certificates",
    name: "Investment Certificates",
    category: "assets",
    requiredFor: ["beneficiary", "petitioner"],
    required: false,
  },
  {
    id: "nra_certificate",
    name: "NRA Certificate",
    category: "assets",
    requiredFor: ["beneficiary"],
    required: false,
  },
  {
    id: "property_docs",
    name: "Property Ownership Documents",
    category: "assets",
    requiredFor: ["beneficiary", "petitioner"],
    required: false,
  },
  {
    id: "vehicle_registration",
    name: "Vehicle Registration Papers",
    category: "assets",
    requiredFor: ["beneficiary", "petitioner"],
    required: false,
  },

  {
    id: "communication_evidence",
    name: "Communication Evidence",
    category: "relationship",
    requiredFor: ["beneficiary", "petitioner"],
    required: true,
  },
  {
    id: "joint_financial_docs",
    name: "Joint Financial Documents",
    category: "relationship",
    requiredFor: ["beneficiary", "petitioner"],
    required: false,
  },
  {
    id: "relationship_photos",
    name: "Relationship Photos",
    category: "relationship",
    requiredFor: ["beneficiary", "petitioner"],
    required: true,
  },
  {
    id: "wedding_photos",
    name: "Wedding Photos",
    category: "relationship",
    requiredFor: ["beneficiary", "petitioner"],
    required: true,
  },

  {
    id: "social_media_list",
    name: "Social Media Platforms List",
    category: "social",
    requiredFor: ["beneficiary"],
    required: false,
  },
  {
    id: "social_media_screenshots",
    name: "Social Media Profile Screenshots",
    category: "social",
    requiredFor: ["beneficiary"],
    required: false,
  },

  {
    id: "fbr_tax_returns",
    name: "FBR Tax Returns",
    category: "tax",
    requiredFor: ["beneficiary", "petitioner"],
    required: false,
  },
  {
    id: "ntn_certificate",
    name: "NTN Certificate",
    category: "tax",
    requiredFor: ["beneficiary", "petitioner"],
    required: false,
  },
  {
    id: "tax_clearance",
    name: "Tax Clearance Certificate",
    category: "tax",
    requiredFor: ["beneficiary", "petitioner"],
    required: false,
  },

  {
    id: "translator_certification",
    name: "Translator Certification",
    category: "translation",
    requiredFor: ["beneficiary"],
    required: false,
  },

  {
    id: "old_passports",
    name: "Old Passport Copies",
    category: "travel",
    requiredFor: ["beneficiary"],
    required: false,
  },
  {
    id: "travel_itineraries",
    name: "Previous Travel Itineraries",
    category: "travel",
    requiredFor: ["beneficiary"],
    required: false,
  },
  {
    id: "visa_stamps",
    name: "Previous Visa Stamps",
    category: "travel",
    requiredFor: ["beneficiary"],
    required: false,
  },
  {
    id: "travel_history",
    name: "Travel History Record",
    category: "travel",
    requiredFor: ["beneficiary"],
    required: false,
  },

  {
    id: "employment_contract",
    name: "Employment Contract (Pakistan)",
    category: "work",
    requiredFor: ["beneficiary"],
    required: false,
  },
  {
    id: "eobi_certificate",
    name: "EOBI Certificate",
    category: "work",
    requiredFor: ["beneficiary"],
    required: false,
  },
  {
    id: "noc",
    name: "No Objection Certificate (NOC)",
    category: "work",
    requiredFor: ["beneficiary"],
    required: false,
  },
  {
    id: "salary_slips",
    name: "Salary Slips",
    category: "work",
    requiredFor: ["beneficiary"],
    required: false,
  },
  {
    id: "experience_letter",
    name: "Work Experience Letter",
    category: "work",
    requiredFor: ["beneficiary"],
    required: false,
  },
];
